name: Package Application
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - run: pip install -r src/requirements.txt
    - run: pyinstaller src/build.spec
    - uses: actions/upload-artifact@v3
      with:
        name: net2_${{matrix.os}}
        path: dist/*
  pack:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download linux binary from build
        uses: actions/download-artifact@v3
        with:
          name: net2_ubuntu-latest
          path: ./net2_ubuntu
      - name: Download Windows binary from build
        uses: actions/download-artifact@v3
        with:
          name: net2_windows-latest
          path: ./net2_windows

      - name: Download Mac binary from build
        uses: actions/download-artifact@v3
        with:
          name: net2_macOs-latest
          path: ./net2_macOs

      - name: Create release
        uses: Roang-zero1/github-create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "net2_*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: make release
      #   uses: marvinpinto/action-automatic-releases@latest
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     files: |
      #       net2_*
